let state;
const $=s=>document.querySelector(s);
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setBusy(el,busy,label){el.disabled=busy;el.textContent=busy?label:el.dataset.label}
async function load(){const notice=$('#health');notice.textContent='Loading workbook…';try{const r=await fetch('/api/summary');if(!r.ok)throw Error(await r.text());state=await r.json();notice.textContent=`Source: ${state.source} · validation issues: ${state.validation_errors.length} · Answer_Key excluded: yes`;renderCards();renderAnalysis()}catch(e){notice.textContent=`Unable to load operations data: ${e.message}`;notice.className='notice error'}}
function renderCards(){$('#cards').innerHTML=Object.entries(state.stages).map(([s,v])=>{let m=v.metrics,a=v.analysis;return `<article class="card"><div class="card-top"><h2>${s}</h2><span class="status ${a.status}">${a.status}</span></div><div class="kpis"><div class="kpi"><strong>${m.good.toLocaleString()}</strong><small>good</small></div><div class="kpi"><strong>${(m.pct_target*100).toFixed(1)}%</strong><small>of target</small></div><div class="kpi"><strong>${m.stop_minutes}</strong><small>stop min</small></div></div><div class="bar"><i style="width:${Math.min(100,m.pct_target*100)}%"></i></div><p class="muted">${m.out_of_spec} out-of-spec · ${m.changes_without_standard} unverified changes</p></article>`}).join('')}
function renderAnalysis(){let s=$('#stage').value,a=state.stages[s].analysis;$('#analysis').innerHTML=`<div class="status ${a.status}">${a.status}${a.quality_hold?' · QA hold':''}</div><div class="cause">${esc(a.cause)}</div><div class="evidence">${a.evidence.map(e=>`<div class="pill"><b>${esc(e.value)}</b><small>${esc(e.label)}</small></div>`).join('')}</div><ul class="actions">${a.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="muted">Escalate to: ${a.escalate_to.join(', ')||'line owner'} · confidence ${(a.confidence*100).toFixed(0)}%</p>`}
$('#refresh').onclick=load;$('#stage').onchange=renderAnalysis;$('#ask').dataset.label='Ask agent';$('#ask').onclick=async()=>{const btn=$('#ask'),answer=$('#answer');answer.textContent='Retrieving evidence and drafting answer…';setBusy(btn,true,'Working…');try{let q=$('#question').value.trim();if(q.length<3)throw Error('Ask a longer question.');let r=await fetch('/api/conversation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q,stage:$('#stage').value})});let x=await r.json();if(!r.ok)throw Error(x.detail||'Request failed');answer.innerHTML=`<b>${esc(x.answer)}</b><div class="citations"><strong>Sources</strong>${(x.citations||[]).map(c=>`<span>[${esc(c.sheet)}:${esc(c.row)}]</span>`).join(' ')||'<span>No source rows returned</span>'}</div>`}catch(e){answer.textContent=`Conversation error: ${e.message}`;answer.className='answer error'}finally{setBusy(btn,false)}};load();
function barChart(title,items,valueKey){if(!items||!items.length)return `<div class="chart"><h3>${title}</h3><p class="muted">No data</p></div>`;const max=Math.max(...items.flatMap(x=>[Number(x[valueKey]||0),Number(x.target||0)]),1);return `<div class="chart"><h3>${title}</h3>${items.map(x=>`<div class="bar-row"><span>${esc(x.label)}</span><i style="width:${Math.max(2,Number(x[valueKey]||0)/max*100)}%"></i><b>${esc(Number(x[valueKey]||0).toFixed(1))}</b></div>${x.target!==undefined?`<div class="bar-row target"><span>target</span><i style="width:${Math.max(2,Number(x.target||0)/max*100)}%"></i><b>${esc(Number(x.target||0).toFixed(1))}</b></div>`:''}`).join('')}</div>`}function loadDrilldown(stage){const el=$('#evidenceDetails');el.innerHTML='<p class="muted">Loading drill-down evidence…</p>';fetch(`/api/rca/${encodeURIComponent(stage)}/evidence`).then(r=>{if(!r.ok)throw Error('Evidence request failed');return r.json()}).then(x=>{const rows=x.supporting_rows||[];el.innerHTML=`<h3>Evidence drill-down</h3><p class="muted">${rows.length} supporting records · ${x.timeline.length} timeline records</p><div class="charts">${barChart('Output vs target',x.charts.output_vs_target,'good')}${barChart('Stop minutes by stage',x.charts.stop_minutes_by_stage,'minutes')}${barChart('Sieve pass',x.charts.sieve_pass,'value')}${barChart('Hammer run hours',x.charts.hammer_run_hours,'value')}</div><h4>Linked records</h4><div class="evidence-table">${rows.slice(0,30).map(r=>`<div><b>${esc(r.sheet)}:${esc(r.row)}</b><span>${esc(r.date||'')} · ${esc(r.payload.Parameter||r.payload.Hour||r.payload.Reason||r.kind)}</span></div>`).join('')||'<p class="muted">No supporting records.</p>'}</div><h4>Actions and owners</h4><ul class="actions">${(x.actions||[]).map(a=>`<li>${esc(a.action)} <span class="muted">(${esc(a.owner)})</span></li>`).join('')}</ul>`}).catch(e=>{el.innerHTML=`<p class="error">${esc(e.message)}</p>`})}

